// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MajorLogin.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MajorLogin.proto</summary>
public static partial class MajorLoginReflection {

  #region Descriptor
  /// <summary>File descriptor for MajorLogin.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MajorLoginReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBNYWpvckxvZ2luLnByb3RvItQKCg1NYWpvckxvZ2luUmVxEgsKA3VpZBgB",
          "IAEoAxISCgpldmVudF90aW1lGAMgASgJEhEKCWdhbWVfbmFtZRgEIAEoCRIT",
          "CgtwbGF0Zm9ybV9pZBgFIAEoBRIWCg5jbGllbnRfdmVyc2lvbhgHIAEoCRIX",
          "Cg9zeXN0ZW1fc29mdHdhcmUYCCABKAkSFwoPc3lzdGVtX2hhcmR3YXJlGAkg",
          "ASgJEhgKEHRlbGVjb21fb3BlcmF0b3IYCiABKAkSFAoMbmV0d29ya190eXBl",
          "GAsgASgJEhQKDHNjcmVlbl93aWR0aBgMIAEoBRIVCg1zY3JlZW5faGVpZ2h0",
          "GA0gASgFEhIKCnNjcmVlbl9kcGkYDiABKAkSGQoRcHJvY2Vzc29yX2RldGFp",
          "bHMYDyABKAkSDgoGbWVtb3J5GBAgASgFEhQKDGdwdV9yZW5kZXJlchgRIAEo",
          "CRITCgtncHVfdmVyc2lvbhgSIAEoCRIYChB1bmlxdWVfZGV2aWNlX2lkGBMg",
          "ASgJEhEKCWNsaWVudF9pcBgUIAEoCRIQCghsYW5ndWFnZRgVIAEoCRIPCgdv",
          "cGVuX2lkGBYgASgJEhQKDG9wZW5faWRfdHlwZRgXIAEoCRITCgtkZXZpY2Vf",
          "dHlwZRgYIAEoCRIUCgxkZXZpY2VfbW9kZWwYGSABKAkSFAoMYWNjZXNzX3Rv",
          "a2VuGB0gASgJEhcKD3BsYXRmb3JtX3Nka19pZBgeIAEoBRIaChJuZXR3b3Jr",
          "X29wZXJhdG9yX2EYKSABKAkSFgoObmV0d29ya190eXBlX2EYKiABKAkSHAoU",
          "Y2xpZW50X3VzaW5nX3ZlcnNpb24YOSABKAkSHgoWZXh0ZXJuYWxfc3RvcmFn",
          "ZV90b3RhbBg8IAEoBRIiChpleHRlcm5hbF9zdG9yYWdlX2F2YWlsYWJsZRg9",
          "IAEoBRIeChZpbnRlcm5hbF9zdG9yYWdlX3RvdGFsGD4gASgFEiIKGmludGVy",
          "bmFsX3N0b3JhZ2VfYXZhaWxhYmxlGD8gASgFEiMKG2dhbWVfZGlza19zdG9y",
          "YWdlX2F2YWlsYWJsZRhAIAEoBRIfChdnYW1lX2Rpc2tfc3RvcmFnZV90b3Rh",
          "bBhBIAEoBRIlCh1leHRlcm5hbF9zZGNhcmRfYXZhaWxfc3RvcmFnZRhCIAEo",
          "BRIlCh1leHRlcm5hbF9zZGNhcmRfdG90YWxfc3RvcmFnZRhDIAEoBRIQCghs",
          "b2dpbl9ieRhJIAEoBRIUCgxsaWJyYXJ5X3BhdGgYSiABKAkSEAoIY3B1X3R5",
          "cGUYTCABKAUSFQoNbGlicmFyeV90b2tlbhhNIAEoCRIUCgxjaGFubmVsX3R5",
          "cGUYTiABKAUSHQoVY3B1X2FyY2hpdGVjdHVyZV9mbGFnGE8gASgFEhgKEGNw",
          "dV9hcmNoaXRlY3R1cmUYUSABKAkSGwoTY2xpZW50X3ZlcnNpb25fY29kZRhT",
          "IAEoCRIUCgxncmFwaGljc19hcGkYViABKAkSHQoVc3VwcG9ydGVkX2FzdGNf",
          "Yml0c2V0GFcgASgFEhoKEmxvZ2luX29wZW5faWRfdHlwZRhYIAEoBRIUCgxs",
          "b2FkaW5nX3RpbWUYXCABKAUSFwoPcmVsZWFzZV9jaGFubmVsGF0gASgJEiAK",
          "GGFuZHJvaWRfZW5naW5lX2luaXRfZmxhZxhfIAEoBRIPCgdpZl9wdXNoGGEg",
          "ASgFEg4KBmlzX3ZwbhhiIAEoBRIcChRvcmlnaW5fcGxhdGZvcm1fdHlwZRhj",
          "IAEoCRIdChVwcmltYXJ5X3BsYXRmb3JtX3R5cGUYZCABKAkiLwoNTWFqb3JM",
          "b2dpblJlcxIRCglhY2NvdW50SWQYASABKAMSCwoDand0GAggASgJYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MajorLoginReq), global::MajorLoginReq.Parser, new[]{ "Uid", "EventTime", "GameName", "PlatformId", "ClientVersion", "SystemSoftware", "SystemHardware", "TelecomOperator", "NetworkType", "ScreenWidth", "ScreenHeight", "ScreenDpi", "ProcessorDetails", "Memory", "GpuRenderer", "GpuVersion", "UniqueDeviceId", "ClientIp", "Language", "OpenId", "OpenIdType", "DeviceType", "DeviceModel", "AccessToken", "PlatformSdkId", "NetworkOperatorA", "NetworkTypeA", "ClientUsingVersion", "ExternalStorageTotal", "ExternalStorageAvailable", "InternalStorageTotal", "InternalStorageAvailable", "GameDiskStorageAvailable", "GameDiskStorageTotal", "ExternalSdcardAvailStorage", "ExternalSdcardTotalStorage", "LoginBy", "LibraryPath", "CpuType", "LibraryToken", "ChannelType", "CpuArchitectureFlag", "CpuArchitecture", "ClientVersionCode", "GraphicsApi", "SupportedAstcBitset", "LoginOpenIdType", "LoadingTime", "ReleaseChannel", "AndroidEngineInitFlag", "IfPush", "IsVpn", "OriginPlatformType", "PrimaryPlatformType" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MajorLoginRes), global::MajorLoginRes.Parser, new[]{ "AccountId", "Jwt" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MajorLoginReq : pb::IMessage<MajorLoginReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MajorLoginReq> _parser = new pb::MessageParser<MajorLoginReq>(() => new MajorLoginReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MajorLoginReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MajorLoginReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginReq(MajorLoginReq other) : this() {
    uid_ = other.uid_;
    eventTime_ = other.eventTime_;
    gameName_ = other.gameName_;
    platformId_ = other.platformId_;
    clientVersion_ = other.clientVersion_;
    systemSoftware_ = other.systemSoftware_;
    systemHardware_ = other.systemHardware_;
    telecomOperator_ = other.telecomOperator_;
    networkType_ = other.networkType_;
    screenWidth_ = other.screenWidth_;
    screenHeight_ = other.screenHeight_;
    screenDpi_ = other.screenDpi_;
    processorDetails_ = other.processorDetails_;
    memory_ = other.memory_;
    gpuRenderer_ = other.gpuRenderer_;
    gpuVersion_ = other.gpuVersion_;
    uniqueDeviceId_ = other.uniqueDeviceId_;
    clientIp_ = other.clientIp_;
    language_ = other.language_;
    openId_ = other.openId_;
    openIdType_ = other.openIdType_;
    deviceType_ = other.deviceType_;
    deviceModel_ = other.deviceModel_;
    accessToken_ = other.accessToken_;
    platformSdkId_ = other.platformSdkId_;
    networkOperatorA_ = other.networkOperatorA_;
    networkTypeA_ = other.networkTypeA_;
    clientUsingVersion_ = other.clientUsingVersion_;
    externalStorageTotal_ = other.externalStorageTotal_;
    externalStorageAvailable_ = other.externalStorageAvailable_;
    internalStorageTotal_ = other.internalStorageTotal_;
    internalStorageAvailable_ = other.internalStorageAvailable_;
    gameDiskStorageAvailable_ = other.gameDiskStorageAvailable_;
    gameDiskStorageTotal_ = other.gameDiskStorageTotal_;
    externalSdcardAvailStorage_ = other.externalSdcardAvailStorage_;
    externalSdcardTotalStorage_ = other.externalSdcardTotalStorage_;
    loginBy_ = other.loginBy_;
    libraryPath_ = other.libraryPath_;
    cpuType_ = other.cpuType_;
    libraryToken_ = other.libraryToken_;
    channelType_ = other.channelType_;
    cpuArchitectureFlag_ = other.cpuArchitectureFlag_;
    cpuArchitecture_ = other.cpuArchitecture_;
    clientVersionCode_ = other.clientVersionCode_;
    graphicsApi_ = other.graphicsApi_;
    supportedAstcBitset_ = other.supportedAstcBitset_;
    loginOpenIdType_ = other.loginOpenIdType_;
    loadingTime_ = other.loadingTime_;
    releaseChannel_ = other.releaseChannel_;
    androidEngineInitFlag_ = other.androidEngineInitFlag_;
    ifPush_ = other.ifPush_;
    isVpn_ = other.isVpn_;
    originPlatformType_ = other.originPlatformType_;
    primaryPlatformType_ = other.primaryPlatformType_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginReq Clone() {
    return new MajorLoginReq(this);
  }

  /// <summary>Field number for the "uid" field.</summary>
  public const int UidFieldNumber = 1;
  private long uid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Uid {
    get { return uid_; }
    set {
      uid_ = value;
    }
  }

  /// <summary>Field number for the "event_time" field.</summary>
  public const int EventTimeFieldNumber = 3;
  private string eventTime_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string EventTime {
    get { return eventTime_; }
    set {
      eventTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "game_name" field.</summary>
  public const int GameNameFieldNumber = 4;
  private string gameName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameName {
    get { return gameName_; }
    set {
      gameName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "platform_id" field.</summary>
  public const int PlatformIdFieldNumber = 5;
  private int platformId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlatformId {
    get { return platformId_; }
    set {
      platformId_ = value;
    }
  }

  /// <summary>Field number for the "client_version" field.</summary>
  public const int ClientVersionFieldNumber = 7;
  private string clientVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientVersion {
    get { return clientVersion_; }
    set {
      clientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "system_software" field.</summary>
  public const int SystemSoftwareFieldNumber = 8;
  private string systemSoftware_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SystemSoftware {
    get { return systemSoftware_; }
    set {
      systemSoftware_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "system_hardware" field.</summary>
  public const int SystemHardwareFieldNumber = 9;
  private string systemHardware_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SystemHardware {
    get { return systemHardware_; }
    set {
      systemHardware_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "telecom_operator" field.</summary>
  public const int TelecomOperatorFieldNumber = 10;
  private string telecomOperator_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string TelecomOperator {
    get { return telecomOperator_; }
    set {
      telecomOperator_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "network_type" field.</summary>
  public const int NetworkTypeFieldNumber = 11;
  private string networkType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NetworkType {
    get { return networkType_; }
    set {
      networkType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "screen_width" field.</summary>
  public const int ScreenWidthFieldNumber = 12;
  private int screenWidth_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ScreenWidth {
    get { return screenWidth_; }
    set {
      screenWidth_ = value;
    }
  }

  /// <summary>Field number for the "screen_height" field.</summary>
  public const int ScreenHeightFieldNumber = 13;
  private int screenHeight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ScreenHeight {
    get { return screenHeight_; }
    set {
      screenHeight_ = value;
    }
  }

  /// <summary>Field number for the "screen_dpi" field.</summary>
  public const int ScreenDpiFieldNumber = 14;
  private string screenDpi_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ScreenDpi {
    get { return screenDpi_; }
    set {
      screenDpi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "processor_details" field.</summary>
  public const int ProcessorDetailsFieldNumber = 15;
  private string processorDetails_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ProcessorDetails {
    get { return processorDetails_; }
    set {
      processorDetails_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "memory" field.</summary>
  public const int MemoryFieldNumber = 16;
  private int memory_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Memory {
    get { return memory_; }
    set {
      memory_ = value;
    }
  }

  /// <summary>Field number for the "gpu_renderer" field.</summary>
  public const int GpuRendererFieldNumber = 17;
  private string gpuRenderer_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GpuRenderer {
    get { return gpuRenderer_; }
    set {
      gpuRenderer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gpu_version" field.</summary>
  public const int GpuVersionFieldNumber = 18;
  private string gpuVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GpuVersion {
    get { return gpuVersion_; }
    set {
      gpuVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "unique_device_id" field.</summary>
  public const int UniqueDeviceIdFieldNumber = 19;
  private string uniqueDeviceId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string UniqueDeviceId {
    get { return uniqueDeviceId_; }
    set {
      uniqueDeviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "client_ip" field.</summary>
  public const int ClientIpFieldNumber = 20;
  private string clientIp_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientIp {
    get { return clientIp_; }
    set {
      clientIp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "language" field.</summary>
  public const int LanguageFieldNumber = 21;
  private string language_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Language {
    get { return language_; }
    set {
      language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "open_id" field.</summary>
  public const int OpenIdFieldNumber = 22;
  private string openId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OpenId {
    get { return openId_; }
    set {
      openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "open_id_type" field.</summary>
  public const int OpenIdTypeFieldNumber = 23;
  private string openIdType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OpenIdType {
    get { return openIdType_; }
    set {
      openIdType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device_type" field.</summary>
  public const int DeviceTypeFieldNumber = 24;
  private string deviceType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DeviceType {
    get { return deviceType_; }
    set {
      deviceType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "device_model" field.</summary>
  public const int DeviceModelFieldNumber = 25;
  private string deviceModel_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DeviceModel {
    get { return deviceModel_; }
    set {
      deviceModel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "access_token" field.</summary>
  public const int AccessTokenFieldNumber = 29;
  private string accessToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AccessToken {
    get { return accessToken_; }
    set {
      accessToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "platform_sdk_id" field.</summary>
  public const int PlatformSdkIdFieldNumber = 30;
  private int platformSdkId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int PlatformSdkId {
    get { return platformSdkId_; }
    set {
      platformSdkId_ = value;
    }
  }

  /// <summary>Field number for the "network_operator_a" field.</summary>
  public const int NetworkOperatorAFieldNumber = 41;
  private string networkOperatorA_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NetworkOperatorA {
    get { return networkOperatorA_; }
    set {
      networkOperatorA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "network_type_a" field.</summary>
  public const int NetworkTypeAFieldNumber = 42;
  private string networkTypeA_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string NetworkTypeA {
    get { return networkTypeA_; }
    set {
      networkTypeA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "client_using_version" field.</summary>
  public const int ClientUsingVersionFieldNumber = 57;
  private string clientUsingVersion_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientUsingVersion {
    get { return clientUsingVersion_; }
    set {
      clientUsingVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "external_storage_total" field.</summary>
  public const int ExternalStorageTotalFieldNumber = 60;
  private int externalStorageTotal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ExternalStorageTotal {
    get { return externalStorageTotal_; }
    set {
      externalStorageTotal_ = value;
    }
  }

  /// <summary>Field number for the "external_storage_available" field.</summary>
  public const int ExternalStorageAvailableFieldNumber = 61;
  private int externalStorageAvailable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ExternalStorageAvailable {
    get { return externalStorageAvailable_; }
    set {
      externalStorageAvailable_ = value;
    }
  }

  /// <summary>Field number for the "internal_storage_total" field.</summary>
  public const int InternalStorageTotalFieldNumber = 62;
  private int internalStorageTotal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int InternalStorageTotal {
    get { return internalStorageTotal_; }
    set {
      internalStorageTotal_ = value;
    }
  }

  /// <summary>Field number for the "internal_storage_available" field.</summary>
  public const int InternalStorageAvailableFieldNumber = 63;
  private int internalStorageAvailable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int InternalStorageAvailable {
    get { return internalStorageAvailable_; }
    set {
      internalStorageAvailable_ = value;
    }
  }

  /// <summary>Field number for the "game_disk_storage_available" field.</summary>
  public const int GameDiskStorageAvailableFieldNumber = 64;
  private int gameDiskStorageAvailable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameDiskStorageAvailable {
    get { return gameDiskStorageAvailable_; }
    set {
      gameDiskStorageAvailable_ = value;
    }
  }

  /// <summary>Field number for the "game_disk_storage_total" field.</summary>
  public const int GameDiskStorageTotalFieldNumber = 65;
  private int gameDiskStorageTotal_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int GameDiskStorageTotal {
    get { return gameDiskStorageTotal_; }
    set {
      gameDiskStorageTotal_ = value;
    }
  }

  /// <summary>Field number for the "external_sdcard_avail_storage" field.</summary>
  public const int ExternalSdcardAvailStorageFieldNumber = 66;
  private int externalSdcardAvailStorage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ExternalSdcardAvailStorage {
    get { return externalSdcardAvailStorage_; }
    set {
      externalSdcardAvailStorage_ = value;
    }
  }

  /// <summary>Field number for the "external_sdcard_total_storage" field.</summary>
  public const int ExternalSdcardTotalStorageFieldNumber = 67;
  private int externalSdcardTotalStorage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ExternalSdcardTotalStorage {
    get { return externalSdcardTotalStorage_; }
    set {
      externalSdcardTotalStorage_ = value;
    }
  }

  /// <summary>Field number for the "login_by" field.</summary>
  public const int LoginByFieldNumber = 73;
  private int loginBy_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LoginBy {
    get { return loginBy_; }
    set {
      loginBy_ = value;
    }
  }

  /// <summary>Field number for the "library_path" field.</summary>
  public const int LibraryPathFieldNumber = 74;
  private string libraryPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LibraryPath {
    get { return libraryPath_; }
    set {
      libraryPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "cpu_type" field.</summary>
  public const int CpuTypeFieldNumber = 76;
  private int cpuType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CpuType {
    get { return cpuType_; }
    set {
      cpuType_ = value;
    }
  }

  /// <summary>Field number for the "library_token" field.</summary>
  public const int LibraryTokenFieldNumber = 77;
  private string libraryToken_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string LibraryToken {
    get { return libraryToken_; }
    set {
      libraryToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "channel_type" field.</summary>
  public const int ChannelTypeFieldNumber = 78;
  private int channelType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ChannelType {
    get { return channelType_; }
    set {
      channelType_ = value;
    }
  }

  /// <summary>Field number for the "cpu_architecture_flag" field.</summary>
  public const int CpuArchitectureFlagFieldNumber = 79;
  private int cpuArchitectureFlag_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CpuArchitectureFlag {
    get { return cpuArchitectureFlag_; }
    set {
      cpuArchitectureFlag_ = value;
    }
  }

  /// <summary>Field number for the "cpu_architecture" field.</summary>
  public const int CpuArchitectureFieldNumber = 81;
  private string cpuArchitecture_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CpuArchitecture {
    get { return cpuArchitecture_; }
    set {
      cpuArchitecture_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "client_version_code" field.</summary>
  public const int ClientVersionCodeFieldNumber = 83;
  private string clientVersionCode_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientVersionCode {
    get { return clientVersionCode_; }
    set {
      clientVersionCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "graphics_api" field.</summary>
  public const int GraphicsApiFieldNumber = 86;
  private string graphicsApi_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GraphicsApi {
    get { return graphicsApi_; }
    set {
      graphicsApi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "supported_astc_bitset" field.</summary>
  public const int SupportedAstcBitsetFieldNumber = 87;
  private int supportedAstcBitset_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int SupportedAstcBitset {
    get { return supportedAstcBitset_; }
    set {
      supportedAstcBitset_ = value;
    }
  }

  /// <summary>Field number for the "login_open_id_type" field.</summary>
  public const int LoginOpenIdTypeFieldNumber = 88;
  private int loginOpenIdType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LoginOpenIdType {
    get { return loginOpenIdType_; }
    set {
      loginOpenIdType_ = value;
    }
  }

  /// <summary>Field number for the "loading_time" field.</summary>
  public const int LoadingTimeFieldNumber = 92;
  private int loadingTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LoadingTime {
    get { return loadingTime_; }
    set {
      loadingTime_ = value;
    }
  }

  /// <summary>Field number for the "release_channel" field.</summary>
  public const int ReleaseChannelFieldNumber = 93;
  private string releaseChannel_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ReleaseChannel {
    get { return releaseChannel_; }
    set {
      releaseChannel_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "android_engine_init_flag" field.</summary>
  public const int AndroidEngineInitFlagFieldNumber = 95;
  private int androidEngineInitFlag_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AndroidEngineInitFlag {
    get { return androidEngineInitFlag_; }
    set {
      androidEngineInitFlag_ = value;
    }
  }

  /// <summary>Field number for the "if_push" field.</summary>
  public const int IfPushFieldNumber = 97;
  private int ifPush_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IfPush {
    get { return ifPush_; }
    set {
      ifPush_ = value;
    }
  }

  /// <summary>Field number for the "is_vpn" field.</summary>
  public const int IsVpnFieldNumber = 98;
  private int isVpn_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int IsVpn {
    get { return isVpn_; }
    set {
      isVpn_ = value;
    }
  }

  /// <summary>Field number for the "origin_platform_type" field.</summary>
  public const int OriginPlatformTypeFieldNumber = 99;
  private string originPlatformType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string OriginPlatformType {
    get { return originPlatformType_; }
    set {
      originPlatformType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "primary_platform_type" field.</summary>
  public const int PrimaryPlatformTypeFieldNumber = 100;
  private string primaryPlatformType_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PrimaryPlatformType {
    get { return primaryPlatformType_; }
    set {
      primaryPlatformType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MajorLoginReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MajorLoginReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Uid != other.Uid) return false;
    if (EventTime != other.EventTime) return false;
    if (GameName != other.GameName) return false;
    if (PlatformId != other.PlatformId) return false;
    if (ClientVersion != other.ClientVersion) return false;
    if (SystemSoftware != other.SystemSoftware) return false;
    if (SystemHardware != other.SystemHardware) return false;
    if (TelecomOperator != other.TelecomOperator) return false;
    if (NetworkType != other.NetworkType) return false;
    if (ScreenWidth != other.ScreenWidth) return false;
    if (ScreenHeight != other.ScreenHeight) return false;
    if (ScreenDpi != other.ScreenDpi) return false;
    if (ProcessorDetails != other.ProcessorDetails) return false;
    if (Memory != other.Memory) return false;
    if (GpuRenderer != other.GpuRenderer) return false;
    if (GpuVersion != other.GpuVersion) return false;
    if (UniqueDeviceId != other.UniqueDeviceId) return false;
    if (ClientIp != other.ClientIp) return false;
    if (Language != other.Language) return false;
    if (OpenId != other.OpenId) return false;
    if (OpenIdType != other.OpenIdType) return false;
    if (DeviceType != other.DeviceType) return false;
    if (DeviceModel != other.DeviceModel) return false;
    if (AccessToken != other.AccessToken) return false;
    if (PlatformSdkId != other.PlatformSdkId) return false;
    if (NetworkOperatorA != other.NetworkOperatorA) return false;
    if (NetworkTypeA != other.NetworkTypeA) return false;
    if (ClientUsingVersion != other.ClientUsingVersion) return false;
    if (ExternalStorageTotal != other.ExternalStorageTotal) return false;
    if (ExternalStorageAvailable != other.ExternalStorageAvailable) return false;
    if (InternalStorageTotal != other.InternalStorageTotal) return false;
    if (InternalStorageAvailable != other.InternalStorageAvailable) return false;
    if (GameDiskStorageAvailable != other.GameDiskStorageAvailable) return false;
    if (GameDiskStorageTotal != other.GameDiskStorageTotal) return false;
    if (ExternalSdcardAvailStorage != other.ExternalSdcardAvailStorage) return false;
    if (ExternalSdcardTotalStorage != other.ExternalSdcardTotalStorage) return false;
    if (LoginBy != other.LoginBy) return false;
    if (LibraryPath != other.LibraryPath) return false;
    if (CpuType != other.CpuType) return false;
    if (LibraryToken != other.LibraryToken) return false;
    if (ChannelType != other.ChannelType) return false;
    if (CpuArchitectureFlag != other.CpuArchitectureFlag) return false;
    if (CpuArchitecture != other.CpuArchitecture) return false;
    if (ClientVersionCode != other.ClientVersionCode) return false;
    if (GraphicsApi != other.GraphicsApi) return false;
    if (SupportedAstcBitset != other.SupportedAstcBitset) return false;
    if (LoginOpenIdType != other.LoginOpenIdType) return false;
    if (LoadingTime != other.LoadingTime) return false;
    if (ReleaseChannel != other.ReleaseChannel) return false;
    if (AndroidEngineInitFlag != other.AndroidEngineInitFlag) return false;
    if (IfPush != other.IfPush) return false;
    if (IsVpn != other.IsVpn) return false;
    if (OriginPlatformType != other.OriginPlatformType) return false;
    if (PrimaryPlatformType != other.PrimaryPlatformType) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Uid != 0L) hash ^= Uid.GetHashCode();
    if (EventTime.Length != 0) hash ^= EventTime.GetHashCode();
    if (GameName.Length != 0) hash ^= GameName.GetHashCode();
    if (PlatformId != 0) hash ^= PlatformId.GetHashCode();
    if (ClientVersion.Length != 0) hash ^= ClientVersion.GetHashCode();
    if (SystemSoftware.Length != 0) hash ^= SystemSoftware.GetHashCode();
    if (SystemHardware.Length != 0) hash ^= SystemHardware.GetHashCode();
    if (TelecomOperator.Length != 0) hash ^= TelecomOperator.GetHashCode();
    if (NetworkType.Length != 0) hash ^= NetworkType.GetHashCode();
    if (ScreenWidth != 0) hash ^= ScreenWidth.GetHashCode();
    if (ScreenHeight != 0) hash ^= ScreenHeight.GetHashCode();
    if (ScreenDpi.Length != 0) hash ^= ScreenDpi.GetHashCode();
    if (ProcessorDetails.Length != 0) hash ^= ProcessorDetails.GetHashCode();
    if (Memory != 0) hash ^= Memory.GetHashCode();
    if (GpuRenderer.Length != 0) hash ^= GpuRenderer.GetHashCode();
    if (GpuVersion.Length != 0) hash ^= GpuVersion.GetHashCode();
    if (UniqueDeviceId.Length != 0) hash ^= UniqueDeviceId.GetHashCode();
    if (ClientIp.Length != 0) hash ^= ClientIp.GetHashCode();
    if (Language.Length != 0) hash ^= Language.GetHashCode();
    if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
    if (OpenIdType.Length != 0) hash ^= OpenIdType.GetHashCode();
    if (DeviceType.Length != 0) hash ^= DeviceType.GetHashCode();
    if (DeviceModel.Length != 0) hash ^= DeviceModel.GetHashCode();
    if (AccessToken.Length != 0) hash ^= AccessToken.GetHashCode();
    if (PlatformSdkId != 0) hash ^= PlatformSdkId.GetHashCode();
    if (NetworkOperatorA.Length != 0) hash ^= NetworkOperatorA.GetHashCode();
    if (NetworkTypeA.Length != 0) hash ^= NetworkTypeA.GetHashCode();
    if (ClientUsingVersion.Length != 0) hash ^= ClientUsingVersion.GetHashCode();
    if (ExternalStorageTotal != 0) hash ^= ExternalStorageTotal.GetHashCode();
    if (ExternalStorageAvailable != 0) hash ^= ExternalStorageAvailable.GetHashCode();
    if (InternalStorageTotal != 0) hash ^= InternalStorageTotal.GetHashCode();
    if (InternalStorageAvailable != 0) hash ^= InternalStorageAvailable.GetHashCode();
    if (GameDiskStorageAvailable != 0) hash ^= GameDiskStorageAvailable.GetHashCode();
    if (GameDiskStorageTotal != 0) hash ^= GameDiskStorageTotal.GetHashCode();
    if (ExternalSdcardAvailStorage != 0) hash ^= ExternalSdcardAvailStorage.GetHashCode();
    if (ExternalSdcardTotalStorage != 0) hash ^= ExternalSdcardTotalStorage.GetHashCode();
    if (LoginBy != 0) hash ^= LoginBy.GetHashCode();
    if (LibraryPath.Length != 0) hash ^= LibraryPath.GetHashCode();
    if (CpuType != 0) hash ^= CpuType.GetHashCode();
    if (LibraryToken.Length != 0) hash ^= LibraryToken.GetHashCode();
    if (ChannelType != 0) hash ^= ChannelType.GetHashCode();
    if (CpuArchitectureFlag != 0) hash ^= CpuArchitectureFlag.GetHashCode();
    if (CpuArchitecture.Length != 0) hash ^= CpuArchitecture.GetHashCode();
    if (ClientVersionCode.Length != 0) hash ^= ClientVersionCode.GetHashCode();
    if (GraphicsApi.Length != 0) hash ^= GraphicsApi.GetHashCode();
    if (SupportedAstcBitset != 0) hash ^= SupportedAstcBitset.GetHashCode();
    if (LoginOpenIdType != 0) hash ^= LoginOpenIdType.GetHashCode();
    if (LoadingTime != 0) hash ^= LoadingTime.GetHashCode();
    if (ReleaseChannel.Length != 0) hash ^= ReleaseChannel.GetHashCode();
    if (AndroidEngineInitFlag != 0) hash ^= AndroidEngineInitFlag.GetHashCode();
    if (IfPush != 0) hash ^= IfPush.GetHashCode();
    if (IsVpn != 0) hash ^= IsVpn.GetHashCode();
    if (OriginPlatformType.Length != 0) hash ^= OriginPlatformType.GetHashCode();
    if (PrimaryPlatformType.Length != 0) hash ^= PrimaryPlatformType.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Uid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Uid);
    }
    if (EventTime.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(EventTime);
    }
    if (GameName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameName);
    }
    if (PlatformId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(PlatformId);
    }
    if (ClientVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(ClientVersion);
    }
    if (SystemSoftware.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SystemSoftware);
    }
    if (SystemHardware.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(SystemHardware);
    }
    if (TelecomOperator.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(TelecomOperator);
    }
    if (NetworkType.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(NetworkType);
    }
    if (ScreenWidth != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(ScreenWidth);
    }
    if (ScreenHeight != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(ScreenHeight);
    }
    if (ScreenDpi.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(ScreenDpi);
    }
    if (ProcessorDetails.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(ProcessorDetails);
    }
    if (Memory != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Memory);
    }
    if (GpuRenderer.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(GpuRenderer);
    }
    if (GpuVersion.Length != 0) {
      output.WriteRawTag(146, 1);
      output.WriteString(GpuVersion);
    }
    if (UniqueDeviceId.Length != 0) {
      output.WriteRawTag(154, 1);
      output.WriteString(UniqueDeviceId);
    }
    if (ClientIp.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(ClientIp);
    }
    if (Language.Length != 0) {
      output.WriteRawTag(170, 1);
      output.WriteString(Language);
    }
    if (OpenId.Length != 0) {
      output.WriteRawTag(178, 1);
      output.WriteString(OpenId);
    }
    if (OpenIdType.Length != 0) {
      output.WriteRawTag(186, 1);
      output.WriteString(OpenIdType);
    }
    if (DeviceType.Length != 0) {
      output.WriteRawTag(194, 1);
      output.WriteString(DeviceType);
    }
    if (DeviceModel.Length != 0) {
      output.WriteRawTag(202, 1);
      output.WriteString(DeviceModel);
    }
    if (AccessToken.Length != 0) {
      output.WriteRawTag(234, 1);
      output.WriteString(AccessToken);
    }
    if (PlatformSdkId != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(PlatformSdkId);
    }
    if (NetworkOperatorA.Length != 0) {
      output.WriteRawTag(202, 2);
      output.WriteString(NetworkOperatorA);
    }
    if (NetworkTypeA.Length != 0) {
      output.WriteRawTag(210, 2);
      output.WriteString(NetworkTypeA);
    }
    if (ClientUsingVersion.Length != 0) {
      output.WriteRawTag(202, 3);
      output.WriteString(ClientUsingVersion);
    }
    if (ExternalStorageTotal != 0) {
      output.WriteRawTag(224, 3);
      output.WriteInt32(ExternalStorageTotal);
    }
    if (ExternalStorageAvailable != 0) {
      output.WriteRawTag(232, 3);
      output.WriteInt32(ExternalStorageAvailable);
    }
    if (InternalStorageTotal != 0) {
      output.WriteRawTag(240, 3);
      output.WriteInt32(InternalStorageTotal);
    }
    if (InternalStorageAvailable != 0) {
      output.WriteRawTag(248, 3);
      output.WriteInt32(InternalStorageAvailable);
    }
    if (GameDiskStorageAvailable != 0) {
      output.WriteRawTag(128, 4);
      output.WriteInt32(GameDiskStorageAvailable);
    }
    if (GameDiskStorageTotal != 0) {
      output.WriteRawTag(136, 4);
      output.WriteInt32(GameDiskStorageTotal);
    }
    if (ExternalSdcardAvailStorage != 0) {
      output.WriteRawTag(144, 4);
      output.WriteInt32(ExternalSdcardAvailStorage);
    }
    if (ExternalSdcardTotalStorage != 0) {
      output.WriteRawTag(152, 4);
      output.WriteInt32(ExternalSdcardTotalStorage);
    }
    if (LoginBy != 0) {
      output.WriteRawTag(200, 4);
      output.WriteInt32(LoginBy);
    }
    if (LibraryPath.Length != 0) {
      output.WriteRawTag(210, 4);
      output.WriteString(LibraryPath);
    }
    if (CpuType != 0) {
      output.WriteRawTag(224, 4);
      output.WriteInt32(CpuType);
    }
    if (LibraryToken.Length != 0) {
      output.WriteRawTag(234, 4);
      output.WriteString(LibraryToken);
    }
    if (ChannelType != 0) {
      output.WriteRawTag(240, 4);
      output.WriteInt32(ChannelType);
    }
    if (CpuArchitectureFlag != 0) {
      output.WriteRawTag(248, 4);
      output.WriteInt32(CpuArchitectureFlag);
    }
    if (CpuArchitecture.Length != 0) {
      output.WriteRawTag(138, 5);
      output.WriteString(CpuArchitecture);
    }
    if (ClientVersionCode.Length != 0) {
      output.WriteRawTag(154, 5);
      output.WriteString(ClientVersionCode);
    }
    if (GraphicsApi.Length != 0) {
      output.WriteRawTag(178, 5);
      output.WriteString(GraphicsApi);
    }
    if (SupportedAstcBitset != 0) {
      output.WriteRawTag(184, 5);
      output.WriteInt32(SupportedAstcBitset);
    }
    if (LoginOpenIdType != 0) {
      output.WriteRawTag(192, 5);
      output.WriteInt32(LoginOpenIdType);
    }
    if (LoadingTime != 0) {
      output.WriteRawTag(224, 5);
      output.WriteInt32(LoadingTime);
    }
    if (ReleaseChannel.Length != 0) {
      output.WriteRawTag(234, 5);
      output.WriteString(ReleaseChannel);
    }
    if (AndroidEngineInitFlag != 0) {
      output.WriteRawTag(248, 5);
      output.WriteInt32(AndroidEngineInitFlag);
    }
    if (IfPush != 0) {
      output.WriteRawTag(136, 6);
      output.WriteInt32(IfPush);
    }
    if (IsVpn != 0) {
      output.WriteRawTag(144, 6);
      output.WriteInt32(IsVpn);
    }
    if (OriginPlatformType.Length != 0) {
      output.WriteRawTag(154, 6);
      output.WriteString(OriginPlatformType);
    }
    if (PrimaryPlatformType.Length != 0) {
      output.WriteRawTag(162, 6);
      output.WriteString(PrimaryPlatformType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Uid != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Uid);
    }
    if (EventTime.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(EventTime);
    }
    if (GameName.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(GameName);
    }
    if (PlatformId != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(PlatformId);
    }
    if (ClientVersion.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(ClientVersion);
    }
    if (SystemSoftware.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(SystemSoftware);
    }
    if (SystemHardware.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(SystemHardware);
    }
    if (TelecomOperator.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(TelecomOperator);
    }
    if (NetworkType.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(NetworkType);
    }
    if (ScreenWidth != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(ScreenWidth);
    }
    if (ScreenHeight != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(ScreenHeight);
    }
    if (ScreenDpi.Length != 0) {
      output.WriteRawTag(114);
      output.WriteString(ScreenDpi);
    }
    if (ProcessorDetails.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(ProcessorDetails);
    }
    if (Memory != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Memory);
    }
    if (GpuRenderer.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(GpuRenderer);
    }
    if (GpuVersion.Length != 0) {
      output.WriteRawTag(146, 1);
      output.WriteString(GpuVersion);
    }
    if (UniqueDeviceId.Length != 0) {
      output.WriteRawTag(154, 1);
      output.WriteString(UniqueDeviceId);
    }
    if (ClientIp.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(ClientIp);
    }
    if (Language.Length != 0) {
      output.WriteRawTag(170, 1);
      output.WriteString(Language);
    }
    if (OpenId.Length != 0) {
      output.WriteRawTag(178, 1);
      output.WriteString(OpenId);
    }
    if (OpenIdType.Length != 0) {
      output.WriteRawTag(186, 1);
      output.WriteString(OpenIdType);
    }
    if (DeviceType.Length != 0) {
      output.WriteRawTag(194, 1);
      output.WriteString(DeviceType);
    }
    if (DeviceModel.Length != 0) {
      output.WriteRawTag(202, 1);
      output.WriteString(DeviceModel);
    }
    if (AccessToken.Length != 0) {
      output.WriteRawTag(234, 1);
      output.WriteString(AccessToken);
    }
    if (PlatformSdkId != 0) {
      output.WriteRawTag(240, 1);
      output.WriteInt32(PlatformSdkId);
    }
    if (NetworkOperatorA.Length != 0) {
      output.WriteRawTag(202, 2);
      output.WriteString(NetworkOperatorA);
    }
    if (NetworkTypeA.Length != 0) {
      output.WriteRawTag(210, 2);
      output.WriteString(NetworkTypeA);
    }
    if (ClientUsingVersion.Length != 0) {
      output.WriteRawTag(202, 3);
      output.WriteString(ClientUsingVersion);
    }
    if (ExternalStorageTotal != 0) {
      output.WriteRawTag(224, 3);
      output.WriteInt32(ExternalStorageTotal);
    }
    if (ExternalStorageAvailable != 0) {
      output.WriteRawTag(232, 3);
      output.WriteInt32(ExternalStorageAvailable);
    }
    if (InternalStorageTotal != 0) {
      output.WriteRawTag(240, 3);
      output.WriteInt32(InternalStorageTotal);
    }
    if (InternalStorageAvailable != 0) {
      output.WriteRawTag(248, 3);
      output.WriteInt32(InternalStorageAvailable);
    }
    if (GameDiskStorageAvailable != 0) {
      output.WriteRawTag(128, 4);
      output.WriteInt32(GameDiskStorageAvailable);
    }
    if (GameDiskStorageTotal != 0) {
      output.WriteRawTag(136, 4);
      output.WriteInt32(GameDiskStorageTotal);
    }
    if (ExternalSdcardAvailStorage != 0) {
      output.WriteRawTag(144, 4);
      output.WriteInt32(ExternalSdcardAvailStorage);
    }
    if (ExternalSdcardTotalStorage != 0) {
      output.WriteRawTag(152, 4);
      output.WriteInt32(ExternalSdcardTotalStorage);
    }
    if (LoginBy != 0) {
      output.WriteRawTag(200, 4);
      output.WriteInt32(LoginBy);
    }
    if (LibraryPath.Length != 0) {
      output.WriteRawTag(210, 4);
      output.WriteString(LibraryPath);
    }
    if (CpuType != 0) {
      output.WriteRawTag(224, 4);
      output.WriteInt32(CpuType);
    }
    if (LibraryToken.Length != 0) {
      output.WriteRawTag(234, 4);
      output.WriteString(LibraryToken);
    }
    if (ChannelType != 0) {
      output.WriteRawTag(240, 4);
      output.WriteInt32(ChannelType);
    }
    if (CpuArchitectureFlag != 0) {
      output.WriteRawTag(248, 4);
      output.WriteInt32(CpuArchitectureFlag);
    }
    if (CpuArchitecture.Length != 0) {
      output.WriteRawTag(138, 5);
      output.WriteString(CpuArchitecture);
    }
    if (ClientVersionCode.Length != 0) {
      output.WriteRawTag(154, 5);
      output.WriteString(ClientVersionCode);
    }
    if (GraphicsApi.Length != 0) {
      output.WriteRawTag(178, 5);
      output.WriteString(GraphicsApi);
    }
    if (SupportedAstcBitset != 0) {
      output.WriteRawTag(184, 5);
      output.WriteInt32(SupportedAstcBitset);
    }
    if (LoginOpenIdType != 0) {
      output.WriteRawTag(192, 5);
      output.WriteInt32(LoginOpenIdType);
    }
    if (LoadingTime != 0) {
      output.WriteRawTag(224, 5);
      output.WriteInt32(LoadingTime);
    }
    if (ReleaseChannel.Length != 0) {
      output.WriteRawTag(234, 5);
      output.WriteString(ReleaseChannel);
    }
    if (AndroidEngineInitFlag != 0) {
      output.WriteRawTag(248, 5);
      output.WriteInt32(AndroidEngineInitFlag);
    }
    if (IfPush != 0) {
      output.WriteRawTag(136, 6);
      output.WriteInt32(IfPush);
    }
    if (IsVpn != 0) {
      output.WriteRawTag(144, 6);
      output.WriteInt32(IsVpn);
    }
    if (OriginPlatformType.Length != 0) {
      output.WriteRawTag(154, 6);
      output.WriteString(OriginPlatformType);
    }
    if (PrimaryPlatformType.Length != 0) {
      output.WriteRawTag(162, 6);
      output.WriteString(PrimaryPlatformType);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Uid != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
    }
    if (EventTime.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(EventTime);
    }
    if (GameName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameName);
    }
    if (PlatformId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlatformId);
    }
    if (ClientVersion.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientVersion);
    }
    if (SystemSoftware.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SystemSoftware);
    }
    if (SystemHardware.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SystemHardware);
    }
    if (TelecomOperator.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(TelecomOperator);
    }
    if (NetworkType.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NetworkType);
    }
    if (ScreenWidth != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ScreenWidth);
    }
    if (ScreenHeight != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ScreenHeight);
    }
    if (ScreenDpi.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ScreenDpi);
    }
    if (ProcessorDetails.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ProcessorDetails);
    }
    if (Memory != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Memory);
    }
    if (GpuRenderer.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(GpuRenderer);
    }
    if (GpuVersion.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(GpuVersion);
    }
    if (UniqueDeviceId.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(UniqueDeviceId);
    }
    if (ClientIp.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientIp);
    }
    if (Language.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Language);
    }
    if (OpenId.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(OpenId);
    }
    if (OpenIdType.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(OpenIdType);
    }
    if (DeviceType.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(DeviceType);
    }
    if (DeviceModel.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(DeviceModel);
    }
    if (AccessToken.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
    }
    if (PlatformSdkId != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(PlatformSdkId);
    }
    if (NetworkOperatorA.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(NetworkOperatorA);
    }
    if (NetworkTypeA.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(NetworkTypeA);
    }
    if (ClientUsingVersion.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientUsingVersion);
    }
    if (ExternalStorageTotal != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ExternalStorageTotal);
    }
    if (ExternalStorageAvailable != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ExternalStorageAvailable);
    }
    if (InternalStorageTotal != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(InternalStorageTotal);
    }
    if (InternalStorageAvailable != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(InternalStorageAvailable);
    }
    if (GameDiskStorageAvailable != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(GameDiskStorageAvailable);
    }
    if (GameDiskStorageTotal != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(GameDiskStorageTotal);
    }
    if (ExternalSdcardAvailStorage != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ExternalSdcardAvailStorage);
    }
    if (ExternalSdcardTotalStorage != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ExternalSdcardTotalStorage);
    }
    if (LoginBy != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(LoginBy);
    }
    if (LibraryPath.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(LibraryPath);
    }
    if (CpuType != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CpuType);
    }
    if (LibraryToken.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(LibraryToken);
    }
    if (ChannelType != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(ChannelType);
    }
    if (CpuArchitectureFlag != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(CpuArchitectureFlag);
    }
    if (CpuArchitecture.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(CpuArchitecture);
    }
    if (ClientVersionCode.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ClientVersionCode);
    }
    if (GraphicsApi.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(GraphicsApi);
    }
    if (SupportedAstcBitset != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(SupportedAstcBitset);
    }
    if (LoginOpenIdType != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(LoginOpenIdType);
    }
    if (LoadingTime != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(LoadingTime);
    }
    if (ReleaseChannel.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(ReleaseChannel);
    }
    if (AndroidEngineInitFlag != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(AndroidEngineInitFlag);
    }
    if (IfPush != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IfPush);
    }
    if (IsVpn != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(IsVpn);
    }
    if (OriginPlatformType.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(OriginPlatformType);
    }
    if (PrimaryPlatformType.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(PrimaryPlatformType);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MajorLoginReq other) {
    if (other == null) {
      return;
    }
    if (other.Uid != 0L) {
      Uid = other.Uid;
    }
    if (other.EventTime.Length != 0) {
      EventTime = other.EventTime;
    }
    if (other.GameName.Length != 0) {
      GameName = other.GameName;
    }
    if (other.PlatformId != 0) {
      PlatformId = other.PlatformId;
    }
    if (other.ClientVersion.Length != 0) {
      ClientVersion = other.ClientVersion;
    }
    if (other.SystemSoftware.Length != 0) {
      SystemSoftware = other.SystemSoftware;
    }
    if (other.SystemHardware.Length != 0) {
      SystemHardware = other.SystemHardware;
    }
    if (other.TelecomOperator.Length != 0) {
      TelecomOperator = other.TelecomOperator;
    }
    if (other.NetworkType.Length != 0) {
      NetworkType = other.NetworkType;
    }
    if (other.ScreenWidth != 0) {
      ScreenWidth = other.ScreenWidth;
    }
    if (other.ScreenHeight != 0) {
      ScreenHeight = other.ScreenHeight;
    }
    if (other.ScreenDpi.Length != 0) {
      ScreenDpi = other.ScreenDpi;
    }
    if (other.ProcessorDetails.Length != 0) {
      ProcessorDetails = other.ProcessorDetails;
    }
    if (other.Memory != 0) {
      Memory = other.Memory;
    }
    if (other.GpuRenderer.Length != 0) {
      GpuRenderer = other.GpuRenderer;
    }
    if (other.GpuVersion.Length != 0) {
      GpuVersion = other.GpuVersion;
    }
    if (other.UniqueDeviceId.Length != 0) {
      UniqueDeviceId = other.UniqueDeviceId;
    }
    if (other.ClientIp.Length != 0) {
      ClientIp = other.ClientIp;
    }
    if (other.Language.Length != 0) {
      Language = other.Language;
    }
    if (other.OpenId.Length != 0) {
      OpenId = other.OpenId;
    }
    if (other.OpenIdType.Length != 0) {
      OpenIdType = other.OpenIdType;
    }
    if (other.DeviceType.Length != 0) {
      DeviceType = other.DeviceType;
    }
    if (other.DeviceModel.Length != 0) {
      DeviceModel = other.DeviceModel;
    }
    if (other.AccessToken.Length != 0) {
      AccessToken = other.AccessToken;
    }
    if (other.PlatformSdkId != 0) {
      PlatformSdkId = other.PlatformSdkId;
    }
    if (other.NetworkOperatorA.Length != 0) {
      NetworkOperatorA = other.NetworkOperatorA;
    }
    if (other.NetworkTypeA.Length != 0) {
      NetworkTypeA = other.NetworkTypeA;
    }
    if (other.ClientUsingVersion.Length != 0) {
      ClientUsingVersion = other.ClientUsingVersion;
    }
    if (other.ExternalStorageTotal != 0) {
      ExternalStorageTotal = other.ExternalStorageTotal;
    }
    if (other.ExternalStorageAvailable != 0) {
      ExternalStorageAvailable = other.ExternalStorageAvailable;
    }
    if (other.InternalStorageTotal != 0) {
      InternalStorageTotal = other.InternalStorageTotal;
    }
    if (other.InternalStorageAvailable != 0) {
      InternalStorageAvailable = other.InternalStorageAvailable;
    }
    if (other.GameDiskStorageAvailable != 0) {
      GameDiskStorageAvailable = other.GameDiskStorageAvailable;
    }
    if (other.GameDiskStorageTotal != 0) {
      GameDiskStorageTotal = other.GameDiskStorageTotal;
    }
    if (other.ExternalSdcardAvailStorage != 0) {
      ExternalSdcardAvailStorage = other.ExternalSdcardAvailStorage;
    }
    if (other.ExternalSdcardTotalStorage != 0) {
      ExternalSdcardTotalStorage = other.ExternalSdcardTotalStorage;
    }
    if (other.LoginBy != 0) {
      LoginBy = other.LoginBy;
    }
    if (other.LibraryPath.Length != 0) {
      LibraryPath = other.LibraryPath;
    }
    if (other.CpuType != 0) {
      CpuType = other.CpuType;
    }
    if (other.LibraryToken.Length != 0) {
      LibraryToken = other.LibraryToken;
    }
    if (other.ChannelType != 0) {
      ChannelType = other.ChannelType;
    }
    if (other.CpuArchitectureFlag != 0) {
      CpuArchitectureFlag = other.CpuArchitectureFlag;
    }
    if (other.CpuArchitecture.Length != 0) {
      CpuArchitecture = other.CpuArchitecture;
    }
    if (other.ClientVersionCode.Length != 0) {
      ClientVersionCode = other.ClientVersionCode;
    }
    if (other.GraphicsApi.Length != 0) {
      GraphicsApi = other.GraphicsApi;
    }
    if (other.SupportedAstcBitset != 0) {
      SupportedAstcBitset = other.SupportedAstcBitset;
    }
    if (other.LoginOpenIdType != 0) {
      LoginOpenIdType = other.LoginOpenIdType;
    }
    if (other.LoadingTime != 0) {
      LoadingTime = other.LoadingTime;
    }
    if (other.ReleaseChannel.Length != 0) {
      ReleaseChannel = other.ReleaseChannel;
    }
    if (other.AndroidEngineInitFlag != 0) {
      AndroidEngineInitFlag = other.AndroidEngineInitFlag;
    }
    if (other.IfPush != 0) {
      IfPush = other.IfPush;
    }
    if (other.IsVpn != 0) {
      IsVpn = other.IsVpn;
    }
    if (other.OriginPlatformType.Length != 0) {
      OriginPlatformType = other.OriginPlatformType;
    }
    if (other.PrimaryPlatformType.Length != 0) {
      PrimaryPlatformType = other.PrimaryPlatformType;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Uid = input.ReadInt64();
          break;
        }
        case 26: {
          EventTime = input.ReadString();
          break;
        }
        case 34: {
          GameName = input.ReadString();
          break;
        }
        case 40: {
          PlatformId = input.ReadInt32();
          break;
        }
        case 58: {
          ClientVersion = input.ReadString();
          break;
        }
        case 66: {
          SystemSoftware = input.ReadString();
          break;
        }
        case 74: {
          SystemHardware = input.ReadString();
          break;
        }
        case 82: {
          TelecomOperator = input.ReadString();
          break;
        }
        case 90: {
          NetworkType = input.ReadString();
          break;
        }
        case 96: {
          ScreenWidth = input.ReadInt32();
          break;
        }
        case 104: {
          ScreenHeight = input.ReadInt32();
          break;
        }
        case 114: {
          ScreenDpi = input.ReadString();
          break;
        }
        case 122: {
          ProcessorDetails = input.ReadString();
          break;
        }
        case 128: {
          Memory = input.ReadInt32();
          break;
        }
        case 138: {
          GpuRenderer = input.ReadString();
          break;
        }
        case 146: {
          GpuVersion = input.ReadString();
          break;
        }
        case 154: {
          UniqueDeviceId = input.ReadString();
          break;
        }
        case 162: {
          ClientIp = input.ReadString();
          break;
        }
        case 170: {
          Language = input.ReadString();
          break;
        }
        case 178: {
          OpenId = input.ReadString();
          break;
        }
        case 186: {
          OpenIdType = input.ReadString();
          break;
        }
        case 194: {
          DeviceType = input.ReadString();
          break;
        }
        case 202: {
          DeviceModel = input.ReadString();
          break;
        }
        case 234: {
          AccessToken = input.ReadString();
          break;
        }
        case 240: {
          PlatformSdkId = input.ReadInt32();
          break;
        }
        case 330: {
          NetworkOperatorA = input.ReadString();
          break;
        }
        case 338: {
          NetworkTypeA = input.ReadString();
          break;
        }
        case 458: {
          ClientUsingVersion = input.ReadString();
          break;
        }
        case 480: {
          ExternalStorageTotal = input.ReadInt32();
          break;
        }
        case 488: {
          ExternalStorageAvailable = input.ReadInt32();
          break;
        }
        case 496: {
          InternalStorageTotal = input.ReadInt32();
          break;
        }
        case 504: {
          InternalStorageAvailable = input.ReadInt32();
          break;
        }
        case 512: {
          GameDiskStorageAvailable = input.ReadInt32();
          break;
        }
        case 520: {
          GameDiskStorageTotal = input.ReadInt32();
          break;
        }
        case 528: {
          ExternalSdcardAvailStorage = input.ReadInt32();
          break;
        }
        case 536: {
          ExternalSdcardTotalStorage = input.ReadInt32();
          break;
        }
        case 584: {
          LoginBy = input.ReadInt32();
          break;
        }
        case 594: {
          LibraryPath = input.ReadString();
          break;
        }
        case 608: {
          CpuType = input.ReadInt32();
          break;
        }
        case 618: {
          LibraryToken = input.ReadString();
          break;
        }
        case 624: {
          ChannelType = input.ReadInt32();
          break;
        }
        case 632: {
          CpuArchitectureFlag = input.ReadInt32();
          break;
        }
        case 650: {
          CpuArchitecture = input.ReadString();
          break;
        }
        case 666: {
          ClientVersionCode = input.ReadString();
          break;
        }
        case 690: {
          GraphicsApi = input.ReadString();
          break;
        }
        case 696: {
          SupportedAstcBitset = input.ReadInt32();
          break;
        }
        case 704: {
          LoginOpenIdType = input.ReadInt32();
          break;
        }
        case 736: {
          LoadingTime = input.ReadInt32();
          break;
        }
        case 746: {
          ReleaseChannel = input.ReadString();
          break;
        }
        case 760: {
          AndroidEngineInitFlag = input.ReadInt32();
          break;
        }
        case 776: {
          IfPush = input.ReadInt32();
          break;
        }
        case 784: {
          IsVpn = input.ReadInt32();
          break;
        }
        case 794: {
          OriginPlatformType = input.ReadString();
          break;
        }
        case 802: {
          PrimaryPlatformType = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Uid = input.ReadInt64();
          break;
        }
        case 26: {
          EventTime = input.ReadString();
          break;
        }
        case 34: {
          GameName = input.ReadString();
          break;
        }
        case 40: {
          PlatformId = input.ReadInt32();
          break;
        }
        case 58: {
          ClientVersion = input.ReadString();
          break;
        }
        case 66: {
          SystemSoftware = input.ReadString();
          break;
        }
        case 74: {
          SystemHardware = input.ReadString();
          break;
        }
        case 82: {
          TelecomOperator = input.ReadString();
          break;
        }
        case 90: {
          NetworkType = input.ReadString();
          break;
        }
        case 96: {
          ScreenWidth = input.ReadInt32();
          break;
        }
        case 104: {
          ScreenHeight = input.ReadInt32();
          break;
        }
        case 114: {
          ScreenDpi = input.ReadString();
          break;
        }
        case 122: {
          ProcessorDetails = input.ReadString();
          break;
        }
        case 128: {
          Memory = input.ReadInt32();
          break;
        }
        case 138: {
          GpuRenderer = input.ReadString();
          break;
        }
        case 146: {
          GpuVersion = input.ReadString();
          break;
        }
        case 154: {
          UniqueDeviceId = input.ReadString();
          break;
        }
        case 162: {
          ClientIp = input.ReadString();
          break;
        }
        case 170: {
          Language = input.ReadString();
          break;
        }
        case 178: {
          OpenId = input.ReadString();
          break;
        }
        case 186: {
          OpenIdType = input.ReadString();
          break;
        }
        case 194: {
          DeviceType = input.ReadString();
          break;
        }
        case 202: {
          DeviceModel = input.ReadString();
          break;
        }
        case 234: {
          AccessToken = input.ReadString();
          break;
        }
        case 240: {
          PlatformSdkId = input.ReadInt32();
          break;
        }
        case 330: {
          NetworkOperatorA = input.ReadString();
          break;
        }
        case 338: {
          NetworkTypeA = input.ReadString();
          break;
        }
        case 458: {
          ClientUsingVersion = input.ReadString();
          break;
        }
        case 480: {
          ExternalStorageTotal = input.ReadInt32();
          break;
        }
        case 488: {
          ExternalStorageAvailable = input.ReadInt32();
          break;
        }
        case 496: {
          InternalStorageTotal = input.ReadInt32();
          break;
        }
        case 504: {
          InternalStorageAvailable = input.ReadInt32();
          break;
        }
        case 512: {
          GameDiskStorageAvailable = input.ReadInt32();
          break;
        }
        case 520: {
          GameDiskStorageTotal = input.ReadInt32();
          break;
        }
        case 528: {
          ExternalSdcardAvailStorage = input.ReadInt32();
          break;
        }
        case 536: {
          ExternalSdcardTotalStorage = input.ReadInt32();
          break;
        }
        case 584: {
          LoginBy = input.ReadInt32();
          break;
        }
        case 594: {
          LibraryPath = input.ReadString();
          break;
        }
        case 608: {
          CpuType = input.ReadInt32();
          break;
        }
        case 618: {
          LibraryToken = input.ReadString();
          break;
        }
        case 624: {
          ChannelType = input.ReadInt32();
          break;
        }
        case 632: {
          CpuArchitectureFlag = input.ReadInt32();
          break;
        }
        case 650: {
          CpuArchitecture = input.ReadString();
          break;
        }
        case 666: {
          ClientVersionCode = input.ReadString();
          break;
        }
        case 690: {
          GraphicsApi = input.ReadString();
          break;
        }
        case 696: {
          SupportedAstcBitset = input.ReadInt32();
          break;
        }
        case 704: {
          LoginOpenIdType = input.ReadInt32();
          break;
        }
        case 736: {
          LoadingTime = input.ReadInt32();
          break;
        }
        case 746: {
          ReleaseChannel = input.ReadString();
          break;
        }
        case 760: {
          AndroidEngineInitFlag = input.ReadInt32();
          break;
        }
        case 776: {
          IfPush = input.ReadInt32();
          break;
        }
        case 784: {
          IsVpn = input.ReadInt32();
          break;
        }
        case 794: {
          OriginPlatformType = input.ReadString();
          break;
        }
        case 802: {
          PrimaryPlatformType = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MajorLoginRes : pb::IMessage<MajorLoginRes>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MajorLoginRes> _parser = new pb::MessageParser<MajorLoginRes>(() => new MajorLoginRes());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MajorLoginRes> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MajorLoginReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginRes() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginRes(MajorLoginRes other) : this() {
    accountId_ = other.accountId_;
    jwt_ = other.jwt_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MajorLoginRes Clone() {
    return new MajorLoginRes(this);
  }

  /// <summary>Field number for the "accountId" field.</summary>
  public const int AccountIdFieldNumber = 1;
  private long accountId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AccountId {
    get { return accountId_; }
    set {
      accountId_ = value;
    }
  }

  /// <summary>Field number for the "jwt" field.</summary>
  public const int JwtFieldNumber = 8;
  private string jwt_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Jwt {
    get { return jwt_; }
    set {
      jwt_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MajorLoginRes);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MajorLoginRes other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (AccountId != other.AccountId) return false;
    if (Jwt != other.Jwt) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (AccountId != 0L) hash ^= AccountId.GetHashCode();
    if (Jwt.Length != 0) hash ^= Jwt.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AccountId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(AccountId);
    }
    if (Jwt.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Jwt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AccountId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(AccountId);
    }
    if (Jwt.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(Jwt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (AccountId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
    }
    if (Jwt.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Jwt);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MajorLoginRes other) {
    if (other == null) {
      return;
    }
    if (other.AccountId != 0L) {
      AccountId = other.AccountId;
    }
    if (other.Jwt.Length != 0) {
      Jwt = other.Jwt;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          AccountId = input.ReadInt64();
          break;
        }
        case 66: {
          Jwt = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          AccountId = input.ReadInt64();
          break;
        }
        case 66: {
          Jwt = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
